FROM n8nio/n8n:latest

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=eva
ENV N8N_BASIC_AUTH_PASSWORD=5678
ENV N8N_USER_MANAGEMENT_DISABLED=true
ENV N8N_PORT=5678
ENV N8N_HOST=0.0.0.0
ENV DB_TYPE=sqlite
ENV N8N_LOG_LEVEL=debug

EXPOSE 5678

ENTRYPOINT ["tini", "--"]
CMD ["n8n"]
